import '../models/development_leap.dart';

/// Saltos/fases de desenvolvimento (0–3 anos) baseados no PDF do produto.
abstract final class DevelopmentLeapsService {
  DevelopmentLeapsService._();

  /// Lista ordenada por idade (minAgeDays).
  static const List<DevelopmentLeap> all = [
    DevelopmentLeap(
      bannerKey: 'dv01',
      rangeLabel: 'Semana 1',
      homeTitle: 'Primeira adaptação',
      homeLead: '{baby_name} pode estar vivendo uma adaptação intensa ao novo ambiente.',
      homeBullets: [
        'quer muito colo',
        'acorda frequentemente',
        'estranha sons e luzes',
        'precisa de contato constante',
      ],
      emotional: 'Tudo ainda é muito novo.',
      detailsWhatsHappening:
          'Seu bebê passou muitos meses em um ambiente silencioso, protegido e quentinho. Agora tudo mudou — e o cérebro ainda está tentando entender luz, frio, fome, sono, toque e sons.',
      keywords: ['adaptação', 'vínculo', 'segurança', 'sensibilidade', 'acolhimento'],
      whatMayHappen: [
        'choros frequentes',
        'despertares frequentes',
        'necessidade constante de colo',
        'sono irregular',
        'maior sensibilidade',
      ],
      howToHelp: ['pele com pele', 'voz calma', 'pouca luz', 'reduzir estímulos', 'acolhimento constante'],
      skillsPossible: ['reconhecer cheiro da mãe', 'reagir a sons', 'reflexos primitivos'],
      emotionalLook: 'Seu bebê ainda não entende rotina. Ele entende presença, calor e segurança.',
      minAgeDays: 0,
      maxAgeDays: 6,
    ),
    DevelopmentLeap(
      bannerKey: 'dv02',
      rangeLabel: 'Semana 2',
      homeTitle: 'Mais atento',
      homeLead: '{baby_name} pode estar começando a perceber melhor vozes e rostos.',
      homeBullets: [
        'observa mais',
        'reconhece vozes',
        'fica atento ao colo',
        'começa pequenas interações',
      ],
      emotional: 'O vínculo emocional continua crescendo.',
      detailsWhatsHappening:
          'O bebê começa lentamente a perceber rostos, vozes, cheiros e presença emocional. A voz da mãe costuma trazer conforto e previsibilidade.',
      keywords: ['reconhecimento', 'conexão', 'conforto', 'presença', 'observação'],
      whatMayHappen: ['mais observação', 'períodos acordado maiores', 'reação à voz', 'mais calma no colo'],
      howToHelp: ['conversar olhando nos olhos', 'cantar músicas suaves', 'contato visual', 'acolhimento'],
      skillsPossible: ['acompanhar rostos', 'reconhecer vozes', 'observar movimentos'],
      emotionalLook: 'Mesmo pequeno, o bebê já começa a construir memórias emocionais.',
      minAgeDays: 7,
      maxAgeDays: 13,
    ),
    DevelopmentLeap(
      bannerKey: 'dv03',
      rangeLabel: 'Semana 3',
      homeTitle: 'Mais sensível',
      homeLead: '{baby_name} pode estar mais sensível ao ambiente.',
      homeBullets: [
        'chora mais no fim do dia',
        'quer mais colo',
        'se irrita facilmente',
        'tem dificuldade para relaxar',
      ],
      emotional: 'O cérebro continua amadurecendo rapidamente.',
      detailsWhatsHappening:
          'O sistema nervoso do bebê ainda está muito imaturo. Tudo pode parecer intenso: sons, luzes, fome, cansaço e estímulos.',
      keywords: ['sensibilidade', 'irritação', 'acolhimento', 'sobrecarga', 'necessidade emocional'],
      whatMayHappen: ['choros no fim do dia', 'agitação', 'dificuldade para dormir', 'necessidade maior de colo'],
      howToHelp: ['ambiente silencioso', 'pouca luz', 'colo', 'embalo suave', 'reduzir estímulos'],
      skillsPossible: ['mais expressões faciais', 'maior atenção ao ambiente'],
      emotionalLook: 'Seu bebê não está “difícil”. Ele ainda está aprendendo a lidar com o mundo.',
      minAgeDays: 14,
      maxAgeDays: 20,
    ),
    DevelopmentLeap(
      bannerKey: 'dv04',
      rangeLabel: 'Semana 4',
      homeTitle: 'Pequenas interações',
      homeLead: '{baby_name} pode estar começando a interagir mais.',
      homeBullets: [
        'observa rostos',
        'acompanha movimentos',
        'demonstra atenção',
        'reage mais às pessoas',
      ],
      emotional: 'O bebê começa a criar conexões sociais.',
      detailsWhatsHappening:
          'O bebê começa a prestar mais atenção, acompanhar pessoas, perceber expressões e reagir ao ambiente.',
      keywords: ['interação', 'atenção', 'observação', 'expressões', 'conexão'],
      whatMayHappen: ['mais atenção visual', 'sons diferentes', 'mais períodos acordado', 'reação social maior'],
      howToHelp: ['conversar bastante', 'fazer expressões faciais', 'mostrar objetos simples', 'respeitar sinais de sono'],
      skillsPossible: ['acompanhar objetos', 'demonstrar interesse social', 'reagir a expressões'],
      emotionalLook: 'O bebê aprende sobre o mundo através das relações.',
      minAgeDays: 21,
      maxAgeDays: 27,
    ),
    DevelopmentLeap(
      bannerKey: 'dv05',
      rangeLabel: 'Semana 5',
      homeTitle: 'Novas descobertas',
      homeLead: '{baby_name} pode estar percebendo mais os próprios movimentos.',
      homeBullets: [
        'observa as mãos',
        'movimenta mais os braços',
        'faz novos sons',
        'fica mais curioso',
      ],
      emotional: 'O corpo começa a ganhar significado.',
      detailsWhatsHappening:
          'O bebê começa a perceber mãos, braços, movimentos e sensações corporais.',
      keywords: ['corpo', 'descoberta', 'coordenação', 'curiosidade', 'movimento'],
      whatMayHappen: ['observar as mãos', 'movimentos repetitivos', 'novos sons', 'mais expressões'],
      howToHelp: ['tummy time', 'brinquedos leves', 'contato visual', 'conversa constante'],
      skillsPossible: ['levantar cabeça', 'observar mãos', 'reagir ao próprio movimento'],
      emotionalLook: 'Cada descoberta ajuda o bebê a construir confiança.',
      minAgeDays: 28,
      maxAgeDays: 34,
    ),
    DevelopmentLeap(
      bannerKey: 'dv06',
      rangeLabel: 'Semana 6',
      homeTitle: 'Mais conectado',
      homeLead: '{baby_name} pode estar mais atento às emoções das pessoas.',
      homeBullets: [
        'observa expressões',
        'reage ao tom de voz',
        'quer mais interação',
        'fica mais sociável',
      ],
      emotional: 'O vínculo emocional continua se fortalecendo.',
      detailsWhatsHappening:
          'O bebê começa a perceber emoções, tom de voz, expressões faciais e presença emocional.',
      keywords: ['emoções', 'vínculo', 'interação', 'segurança', 'presença'],
      whatMayHappen: ['mais sorrisos', 'sons diferentes', 'busca por interação', 'mais atenção social'],
      howToHelp: ['sorrir para o bebê', 'conversar frequentemente', 'usar voz tranquila', 'interagir com calma'],
      skillsPossible: ['sorriso social', 'reação emocional', 'interação maior'],
      emotionalLook: 'Seu bebê aprende segurança através das interações diárias.',
      minAgeDays: 35,
      maxAgeDays: 41,
    ),
    DevelopmentLeap(
      bannerKey: 'dv07',
      rangeLabel: 'Semana 7–8',
      homeTitle: 'Sono diferente',
      homeLead: '{baby_name} pode estar passando por mudanças importantes no sono.',
      homeBullets: [
        'acorda mais',
        'dorme leve',
        'fica mais irritado',
        'precisa mais de acolhimento',
      ],
      emotional: 'O cérebro está amadurecendo rapidamente.',
      detailsWhatsHappening:
          'O cérebro começa a criar ciclos de sono mais complexos. O sono deixa de ser totalmente profundo e passa a ter transições, despertares e ciclos mais leves.',
      keywords: ['sono', 'despertares', 'sensibilidade', 'maturação cerebral', 'irritação'],
      whatMayHappen: ['cochilos curtos', 'mais despertares', 'irritação', 'dificuldade para relaxar'],
      howToHelp: ['rotina leve', 'ambiente escuro', 'menos estímulos', 'respeitar sinais de sono'],
      skillsPossible: ['mais interação', 'curiosidade maior', 'novas expressões'],
      emotionalLook: 'Mudanças no sono não significam regressão. O cérebro está evoluindo.',
      minAgeDays: 42,
      maxAgeDays: 55,
    ),
    DevelopmentLeap(
      bannerKey: 'dv08',
      rangeLabel: '2–3 meses',
      homeTitle: 'Mais consciente',
      homeLead: '{baby_name} pode estar percebendo mais o próprio corpo e o ambiente.',
      homeBullets: [
        'observa as mãos',
        'faz novos sons',
        'demonstra mais curiosidade',
        'reage mais às pessoas',
      ],
      emotional: 'Pequenas descobertas acontecem todos os dias.',
      detailsWhatsHappening:
          'O bebê começa a perceber que consegue interagir com o ambiente. Ele aprende movimento, resposta emocional, coordenação e percepção visual.',
      keywords: ['consciência corporal', 'coordenação', 'curiosidade', 'descoberta', 'percepção'],
      whatMayHappen: ['movimentos repetitivos', 'observação intensa', 'mais interação', 'novos sons'],
      howToHelp: ['tummy time', 'brinquedos simples', 'interação visual', 'conversas suaves'],
      skillsPossible: ['levantar mais a cabeça', 'observar objetos', 'reagir ao ambiente'],
      emotionalLook: 'Cada nova descoberta fortalece a confiança do bebê.',
      minAgeDays: 56,
      maxAgeDays: 89,
    ),
    DevelopmentLeap(
      bannerKey: 'dv09',
      rangeLabel: '3–4 meses',
      homeTitle: 'Muito mais interação',
      homeLead: '{baby_name} pode estar muito mais sociável.',
      homeBullets: [
        'ri mais',
        'responde às pessoas',
        'faz sons',
        'quer brincar',
      ],
      emotional: 'O vínculo social cresce rapidamente.',
      detailsWhatsHappening:
          'O bebê começa a perceber melhor emoções, vozes, expressões e interação social.',
      keywords: ['socialização', 'gargalhadas', 'comunicação', 'expressões', 'vínculo'],
      whatMayHappen: ['mais risadas', 'sons repetitivos', 'maior interação', 'busca por brincadeiras'],
      howToHelp: ['brincar bastante', 'fazer expressões', 'responder aos sons', 'conversar frequentemente'],
      skillsPossible: ['gargalhadas', 'reação emocional intensa', 'interesse social'],
      emotionalLook: 'Seu bebê aprende amor e segurança através das interações.',
      minAgeDays: 90,
      maxAgeDays: 119,
    ),
    DevelopmentLeap(
      bannerKey: 'dv10',
      rangeLabel: '4–5 meses',
      homeTitle: 'Explorando mais',
      homeLead: '{baby_name} pode estar muito mais curioso.',
      homeBullets: [
        'tenta pegar objetos',
        'leva coisas à boca',
        'observa detalhes',
        'quer explorar',
      ],
      emotional: 'O aprendizado acontece através da experiência.',
      detailsWhatsHappening:
          'O bebê desenvolve coordenação, curiosidade intensa, exploração sensorial e percepção espacial.',
      keywords: ['exploração', 'coordenação', 'curiosidade', 'sensações', 'descoberta'],
      whatMayHappen: ['pegar objetos', 'levar itens à boca', 'mais energia', 'mais atenção visual'],
      howToHelp: ['brinquedos seguros', 'estímulos variados', 'supervisão constante', 'permitir exploração'],
      skillsPossible: ['rolar', 'alcançar objetos', 'manipular brinquedos'],
      emotionalLook: 'Explorar é a principal forma de aprendizado nessa fase.',
      minAgeDays: 120,
      maxAgeDays: 149,
    ),
    DevelopmentLeap(
      bannerKey: 'dv11',
      rangeLabel: '5–6 meses',
      homeTitle: 'Mais comunicação',
      homeLead: '{baby_name} pode estar tentando interagir cada vez mais.',
      homeBullets: [
        'faz novos sons',
        'responde às pessoas',
        'quer brincar',
        'demonstra emoções',
      ],
      emotional: 'A comunicação começa a ganhar força.',
      detailsWhatsHappening:
          'O bebê aprende interação social, troca emocional, comunicação inicial e resposta ao ambiente.',
      keywords: ['linguagem', 'comunicação', 'interação', 'socialização', 'vínculo'],
      whatMayHappen: ['balbucios', 'mais risadas', 'interação constante', 'busca por atenção'],
      howToHelp: ['responder aos sons', 'conversar muito', 'brincar frequentemente', 'cantar músicas'],
      skillsPossible: ['balbuciar', 'responder ao nome', 'mais expressão emocional'],
      emotionalLook: 'O bebê aprende conexão antes mesmo das palavras.',
      minAgeDays: 150,
      maxAgeDays: 179,
    ),
    DevelopmentLeap(
      bannerKey: 'dv12',
      rangeLabel: '6–7 meses',
      homeTitle: 'Mundo maior',
      homeLead: '{baby_name} pode estar percebendo melhor o espaço e o ambiente.',
      homeBullets: [
        'quer explorar',
        'observa mais',
        'tenta alcançar coisas',
        'demonstra curiosidade intensa',
      ],
      emotional: 'O mundo parece cada vez maior.',
      detailsWhatsHappening:
          'O bebê começa a compreender distância, espaço, movimento, exploração.',
      keywords: ['percepção espacial', 'exploração', 'curiosidade', 'movimento', 'descoberta'],
      whatMayHappen: ['querer se movimentar', 'explorar objetos', 'mais atenção ao ambiente', 'mais energia'],
      howToHelp: ['permitir exploração segura', 'brinquedos variados', 'espaço livre supervisionado'],
      skillsPossible: ['arrastar', 'alcançar objetos distantes', 'sentar melhor'],
      emotionalLook: 'Explorar o ambiente ajuda o bebê a construir confiança.',
      minAgeDays: 180,
      maxAgeDays: 209,
    ),
    DevelopmentLeap(
      bannerKey: 'dv13',
      rangeLabel: '7–8 meses',
      homeTitle: 'Mais apego',
      homeLead: '{baby_name} pode estar vivendo uma fase de maior necessidade emocional.',
      homeBullets: [
        'quer mais colo',
        'estranha pessoas',
        'chora quando você sai',
        'fica mais sensível',
      ],
      emotional: 'O vínculo emocional se fortalece.',
      detailsWhatsHappening:
          'O bebê começa a compreender ausência, distância, separação e retorno.',
      keywords: ['apego', 'vínculo', 'ansiedade de separação', 'segurança emocional', 'sensibilidade'],
      whatMayHappen: ['mais choros', 'dificuldade para dormir sozinho', 'necessidade de colo', 'estranhar desconhecidos'],
      howToHelp: ['despedidas leves', 'acolhimento', 'previsibilidade', 'presença emocional'],
      skillsPossible: ['reconhecer ausência', 'procurar a mãe', 'responder emocionalmente'],
      emotionalLook: 'Seu bebê não está “manhoso”. Ele está aprendendo sobre segurança emocional.',
      minAgeDays: 210,
      maxAgeDays: 239,
    ),
    DevelopmentLeap(
      bannerKey: 'dv14',
      rangeLabel: '8–9 meses',
      homeTitle: 'Muitas conexões',
      homeLead: '{baby_name} pode estar criando novas conexões rapidamente.',
      homeBullets: [
        'observa muito',
        'reage mais',
        'aprende rápido',
        'explora constantemente',
      ],
      emotional: 'O cérebro está extremamente ativo.',
      detailsWhatsHappening:
          'O bebê começa a desenvolver lógica básica, causa e efeito, permanência de objetos e reconhecimento de padrões.',
      keywords: ['lógica', 'conexões', 'observação', 'aprendizado', 'padrões'],
      whatMayHappen: ['brincar escondendo objetos', 'repetir ações', 'curiosidade intensa', 'explorar reações'],
      howToHelp: ['brincadeiras simples', 'esconder brinquedos', 'músicas repetitivas', 'interação constante'],
      skillsPossible: ['bater palmas', 'engatinhar', 'procurar objetos'],
      emotionalLook: 'O bebê aprende muito através da repetição.',
      minAgeDays: 240,
      maxAgeDays: 269,
    ),
    DevelopmentLeap(
      bannerKey: 'dv15',
      rangeLabel: '9–10 meses',
      homeTitle: 'Não para quieto',
      homeLead: '{baby_name} pode estar em uma fase de muita movimentação.',
      homeBullets: [
        'quer explorar tudo',
        'tenta se mover constantemente',
        'mexe em objetos',
        'demonstra muita energia',
      ],
      emotional: 'O corpo e o cérebro trabalham juntos nessa fase.',
      detailsWhatsHappening:
          'O bebê percebe que consegue agir no ambiente: empurra, abre, alcança, joga e explora.',
      keywords: ['movimento', 'coordenação', 'exploração', 'curiosidade', 'autonomia'],
      whatMayHappen: ['agitação', 'exploração intensa', 'mais tombos', 'dificuldade para ficar parado'],
      howToHelp: ['ambiente seguro', 'permitir exploração', 'supervisão constante', 'brinquedos sensoriais'],
      skillsPossible: ['levantar', 'apoiar em móveis', 'explorar a casa'],
      emotionalLook: 'Explorar é a forma do bebê entender o mundo.',
      minAgeDays: 270,
      maxAgeDays: 299,
    ),
    DevelopmentLeap(
      bannerKey: 'dv16',
      rangeLabel: '10–11 meses',
      homeTitle: 'Tentando se comunicar',
      homeLead: '{baby_name} pode estar observando e imitando muito mais.',
      homeBullets: [
        'repete sons',
        'observa expressões',
        'tenta interagir',
        'responde mais às pessoas',
      ],
      emotional: 'A comunicação ganha força.',
      detailsWhatsHappening:
          'O bebê descobre que sons têm significado, gestos geram respostas e comunicação aproxima pessoas.',
      keywords: ['linguagem', 'imitação', 'comunicação', 'expressão', 'interação'],
      whatMayHappen: ['sons repetitivos', 'tentativa de chamar atenção', 'mais expressões', 'observação intensa'],
      howToHelp: ['conversar bastante', 'nomear objetos', 'responder aos sons', 'ler livros simples'],
      skillsPossible: ['apontar', 'repetir sons', 'entender palavras simples'],
      emotionalLook: 'Antes das palavras, o bebê aprende conexão através da comunicação.',
      minAgeDays: 300,
      maxAgeDays: 329,
    ),
    DevelopmentLeap(
      bannerKey: 'dv17',
      rangeLabel: '11–12 meses',
      homeTitle: 'Mais autonomia',
      homeLead: '{baby_name} pode estar tentando fazer mais coisas sozinho.',
      homeBullets: [
        'tenta andar',
        'explora tudo',
        'demonstra preferências',
        'testa limites',
      ],
      emotional: 'A independência começa a aparecer.',
      detailsWhatsHappening:
          'O bebê percebe que pode agir sozinho no ambiente. Isso traz entusiasmo, curiosidade, insegurança e frustração.',
      keywords: ['autonomia', 'independência', 'exploração', 'confiança', 'movimento'],
      whatMayHappen: ['tentativas de andar', 'resistência a ajuda', 'exploração intensa', 'frustrações rápidas'],
      howToHelp: ['incentivar tentativas', 'ambiente seguro', 'acolher frustrações', 'celebrar conquistas'],
      skillsPossible: ['primeiros passos', 'primeiras palavras', 'mais autonomia'],
      emotionalLook: 'Cada tentativa constrói confiança.',
      minAgeDays: 330,
      maxAgeDays: 364,
    ),
    DevelopmentLeap(
      bannerKey: 'dv18',
      rangeLabel: '12–18 meses',
      homeTitle: 'Muitas emoções',
      homeLead: '{baby_name} pode estar vivendo emoções mais intensas.',
      homeBullets: [
        'quer independência',
        'se frustra facilmente',
        'muda rápido de humor',
        'demonstra personalidade',
      ],
      emotional: 'O mundo emocional está crescendo rapidamente.',
      detailsWhatsHappening:
          'A criança começa a perceber vontades próprias, limites, desejos e frustrações — mas ainda não consegue regular emoções sozinha.',
      keywords: ['emoções', 'autonomia', 'frustração', 'personalidade', 'sensibilidade'],
      whatMayHappen: ['choros intensos', 'irritação', 'resistência', 'busca por independência'],
      howToHelp: ['acolher emoções', 'nomear sentimentos', 'manter calma', 'reforçar segurança emocional'],
      skillsPossible: ['comer sozinho', 'andar melhor', 'imitar adultos', 'falar mais palavras'],
      emotionalLook: 'A criança ainda está aprendendo a lidar com emoções grandes demais para a idade.',
      minAgeDays: 365,
      maxAgeDays: 548,
    ),
    DevelopmentLeap(
      bannerKey: 'dv19',
      rangeLabel: '18–24 meses',
      homeTitle: 'Faz de conta',
      homeLead: '{baby_name} pode estar entrando em uma fase de imaginação intensa.',
      homeBullets: [
        'brinca diferente',
        'cria histórias',
        'conversa mais',
        'demonstra criatividade',
      ],
      emotional: 'A imaginação começa a florescer.',
      detailsWhatsHappening:
          'A criança começa a desenvolver pensamento simbólico, criatividade, imaginação e linguagem mais complexa.',
      keywords: ['imaginação', 'criatividade', 'linguagem', 'brincadeira', 'expressão'],
      whatMayHappen: ['brincadeiras de faz de conta', 'mais perguntas', 'histórias inventadas', 'fala acelerada'],
      howToHelp: ['brincadeiras livres', 'leitura', 'músicas', 'desenhos', 'conversas frequentes'],
      skillsPossible: ['frases maiores', 'brincadeiras simbólicas', 'maior interação social'],
      emotionalLook: 'Imaginar é uma forma importante de construir inteligência emocional.',
      minAgeDays: 549,
      maxAgeDays: 730,
    ),
    DevelopmentLeap(
      bannerKey: 'dv20',
      rangeLabel: '2–3 anos',
      homeTitle: 'Grande personalidade',
      homeLead: '{baby_name} pode estar vivendo uma fase de muita independência e imaginação.',
      homeBullets: [
        'faz muitas perguntas',
        'quer decidir tudo',
        'demonstra emoções fortes',
        'cria histórias',
      ],
      emotional: 'A identidade da criança cresce rapidamente.',
      detailsWhatsHappening:
          'A criança desenvolve identidade própria, imaginação intensa, linguagem avançada e emoções mais complexas.',
      keywords: ['personalidade', 'independência', 'imaginação', 'emoções', 'criatividade'],
      whatMayHappen: ['muitas perguntas', 'mudanças rápidas de humor', 'necessidade de independência', 'brincadeiras imaginativas'],
      howToHelp: ['incentivar criatividade', 'conversar bastante', 'ajudar a nomear emoções', 'dar pequenas responsabilidades'],
      skillsPossible: ['contar histórias', 'criar personagens', 'conversar claramente', 'resolver pequenas situações'],
      emotionalLook: 'Cada criança possui seu próprio ritmo. Comparações podem gerar ansiedade desnecessária.',
      minAgeDays: 731,
      maxAgeDays: 1095,
    ),
  ];

  static int ageDays({required DateTime birthDate, required DateTime now}) {
    final b = DateTime(birthDate.year, birthDate.month, birthDate.day);
    final n = DateTime(now.year, now.month, now.day);
    return n.difference(b).inDays;
  }

  /// Fase atual pela idade (em dias). Retorna null se não houver fase aplicável.
  static DevelopmentLeap? current({required DateTime birthDate, DateTime? now}) {
    final d = ageDays(birthDate: birthDate, now: now ?? DateTime.now());
    for (final leap in all) {
      if (d >= leap.minAgeDays && d <= leap.maxAgeDays) return leap;
    }
    return null;
  }
}

