#!/usr/bin/env python3
"""Translate PT leap JSON to other locales via deep-translator.

Writes tool/leap_trans/<code>.json per language, then assembles
lib/i18n/development_leaps_translated.dart from *all* JSON files found.

LEAP_LANGS=fr,de — only translate those languages (default: full list).

Assemble-only: LEAP_LANGS= python tool/pt_to_es_leaps.py --assemble
(useful after copying JSON files).
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

from deep_translator import GoogleTranslator

ROOT = Path(__file__).resolve().parents[1]
PT_PATH = ROOT / "tool" / "pt_leaps.json"
TRANS_DIR = ROOT / "tool" / "leap_trans"
OUT_DART = ROOT / "lib" / "i18n" / "development_leaps_translated.dart"

_ALL_LANGS: list[tuple[str, str]] = [
    ("es", "es"),
    ("fr", "fr"),
    ("de", "de"),
    ("it", "it"),
    ("hi", "hi"),
    ("id", "id"),
    ("ja", "ja"),
    ("ko", "ko"),
    ("ru", "ru"),
    ("tr", "tr"),
    ("zh", "zh-CN"),
]

_raw = os.environ.get("LEAP_LANGS", "").strip()


def _google_target(code: str) -> str:
    if code == "zh":
        return "zh-CN"
    return code


def _parse_langs_env() -> list[tuple[str, str]]:
    if not _raw:
        return list(_ALL_LANGS)
    return [(p.strip(), _google_target(p.strip())) for p in _raw.split(",") if p.strip()]


LANGS: list[tuple[str, str]] = _parse_langs_env()


def esc_dart(s: str) -> str:
    return (
        s.replace("\\", "\\\\")
        .replace("$", r"\$")
        .replace("'", r"\'")
        .replace("\n", "\\n")
    )


def translate_blob(translator: GoogleTranslator, text: str) -> str:
    if not text.strip():
        return text
    return translator.translate(text)


def _const_name(code: str) -> str:
    """Dart private const identifier for a locale code."""
    return "_leap" + code.upper()


def assemble_dart() -> None:
    blobs: dict[str, dict[str, str]] = {}
    TRANS_DIR.mkdir(parents=True, exist_ok=True)
    for json_path in sorted(TRANS_DIR.glob("*.json")):
        code = json_path.stem
        blobs[code] = json.loads(json_path.read_text(encoding="utf-8"))

    if not blobs:
        raise SystemExit(f"No JSON files in {TRANS_DIR}")

    keys = sorted(set().union(*(set(m.keys()) for m in blobs.values())))
    ordered_codes = [c for c, _ in _ALL_LANGS if c in blobs]

    lines: list[str] = [
        "// GENERATED by tool/pt_to_es_leaps.py from Portuguese leap strings.",
        "// Per-language caches: tool/leap_trans/<code>.json",
        "// ignore_for_file: lines_longer_than_80_chars",
        "",
        "const Map<String, Map<String, String>> kDevelopmentLeapsTranslated = {",
    ]
    for c in ordered_codes:
        lines.append(f"  '{c}': {_const_name(c)},")
    lines.append("};")
    lines.append("")

    for c in ordered_codes:
        lines.append(f"const Map<String, String> {_const_name(c)} = {{")
        m = blobs[c]
        for k in keys:
            lines.append(f"  '{k}': '{esc_dart(m[k])}',")
        lines.append("};")
        lines.append("")

    OUT_DART.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", OUT_DART, "locales:", ", ".join(ordered_codes))


def translate_selected(keys: list[str], data: dict[str, str]) -> None:
    TRANS_DIR.mkdir(parents=True, exist_ok=True)
    for dart_key, tgt in LANGS:
        print("translating", dart_key, "<- pt ->", tgt)
        tr = GoogleTranslator(source="pt", target=tgt)
        m: dict[str, str] = {}
        for i, k in enumerate(keys):
            if i % 50 == 0:
                print(" ", i, "/", len(keys))
            try:
                m[k] = translate_blob(tr, data[k])
            except Exception as e:
                print("fail", k, e)
                m[k] = data[k]
            time.sleep(0.05)
        (TRANS_DIR / f"{dart_key}.json").write_text(
            json.dumps(m, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        print("saved", TRANS_DIR / f"{dart_key}.json")


def main() -> None:
    if "--assemble" in sys.argv:
        assemble_dart()
        return

    data = json.loads(PT_PATH.read_text(encoding="utf-8"))
    keys = sorted(data.keys())
    if LANGS:
        translate_selected(keys, data)
    assemble_dart()


if __name__ == "__main__":
    main()
